In [105]:
import numpy as np

# goal: compute the singular value decomposition (SVD) into A = U S V^T

A = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [0, 1, 0],
    [1, 1, 0]
])

m, n = np.shape(A)
# compute A^TA
A_tr_A = A.T @ A
A_tr_A

eigenvalues, eigenvectors = np.linalg.eig(A_tr_A)
# need to arrange in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

print(f"The computed eigenvalues are:\n {eigenvalues}\n")
print(f"The corresponding eigenvectors are:\n {eigenvectors}\n")

# singular values are the positive square roots of the nonzero eigenvalues of A^T.A
s_i = np.sqrt(eigenvalues)

S = np.zeros((m, n)) # creates a matrix with the same size as A
np.fill_diagonal(S, s_i) # filling in diagonal points with singular values

print(f"The singular values are:\n {s_i}\n")
print(f"The singular value matrix S is: \n{S}\n")

# V should be n x n
V = eigenvectors
V_tr = V.T

print(f"The orthogonal (n x n) matrix V is:\n {V}\n")
print(f"The transpose of the matrix V is:\n {V_tr}\n")

# U should be (m x m)
U = np.zeros((m, m))

for i in range(n):
    U[:, i] = (1 / s_i[i]) * A @ V[:, i]

# need to find column vectors u_4 and u_5 such that U is orthogonal (i.e. all columns are linearly independent and orthonormal)

u1, u2, u3 = U[:, 0], U[:, 1], U[:, 2]

X1 = u1
X2 = u2
X3 = u3
# Perform Gram-Schmidt process
X4 = np.random.rand(m)
X4 = X4 - np.dot(u1, X4) / np.dot(u1, u1) * u1 - np.dot(u2, X4) / np.dot(u2, u2) * u2 - np.dot(u3, X4) / np.dot(u3, u3) * u3
X4 = X4 / np.linalg.norm(X4)
X5 = np.random.rand(m)
X5 = X5 - np.dot(u1, X5) / np.dot(u1, u1) * u1 - np.dot(u2, X5) / np.dot(u2, u2) * u2 - np.dot(u3, X5) / np.dot(u3, u3) * u3 - np.dot(X4, X5) / np.dot(X4, X4) * X4
X5 = X5 / np.linalg.norm(X5)

U[:, -2] = X4
U[:, -1] = X5

print(f"The orthogonal (m x m) matrix U is:\n {U}\n")

print("The matrix A can be represented as the matrix decomposition: A = U S V^T")

The computed eigenvalues are:
 [5. 2. 1.]

The corresponding eigenvectors are:
 [[-4.08248290e-01  5.77350269e-01 -7.07106781e-01]
 [-8.16496581e-01 -5.77350269e-01  5.42510932e-16]
 [-4.08248290e-01  5.77350269e-01  7.07106781e-01]]

The singular values are:
 [2.23606798 1.41421356 1.        ]

The singular value matrix S is: 
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

The orthogonal (n x n) matrix V is:
 [[-4.08248290e-01  5.77350269e-01 -7.07106781e-01]
 [-8.16496581e-01 -5.77350269e-01  5.42510932e-16]
 [-4.08248290e-01  5.77350269e-01  7.07106781e-01]]

The transpose of the matrix V is:
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [ 5.77350269e-01 -5.77350269e-01  5.77350269e-01]
 [-7.07106781e-01  5.42510932e-16  7.07106781e-01]]

The orthogonal (m x m) matrix U is:
 [[-3.65148372e-01  8.16496581e-01  2.69385278e-17  3.99190667e-01
   

In [102]:
# A[0] # returns 1st row
# A[:, 0] # returns 1st column

# A[0: 1] # returns  1st row and stops before 2nd row
# A[0: 2] 